### ISSUE TITLE
提点需求，希望能完善该项目

### ISSUE THREAD

**Issue by Kelephant** [0x1abin/MultiTimer#13]
1. 支持其他线程在我这个定时器里创建任务
2. 支持定时任务的循环执行，每隔一个timeout就执行一次
3. 支持在定时器任务回调里创建新的定时器任务

如果作者允许的话，我可以为该工程实现以上需求，谢谢！

**Comment by cancundiudiu** [comment]
感觉很多功能其实作为开发者，已经完全可以自定义了。提供一个最精简的核心其实挺好的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kelephant ***@***.***&gt;
发送时间: 2022年3月8日 21:54
收件人: 0x1abin/MultiTimer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [0x1abin/MultiTimer] 提点需求，希望能完善该项目 (Issue #13)





  
支持其他线程在我这个定时器里创建任务 

支持定时任务的循环执行，每隔一个timeout就执行一次 

支持在定时器任务回调里创建新的定时器任务 
 
如果作者允许的话，我可以为该工程实现以上需求，谢谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
